OWNER=christian
IMAGE_NAME=nyu:roots
QNAME=$(OWNER)/$(IMAGE_NAME)
DIR=/home/christian/Documents/tmp/roots-test/ci-wp-test

GIT_TAG=$(QNAME):$(TRAVIS_COMMIT)
BUILD_TAG=$(QNAME):0.1.$(TRAVIS_BUILD_NUMBER)
LATEST_TAG=$(QNAME):latest

cbuild:
	echo "Owner: " $(OWNER)

lint: 
	docker run -it --rm --mount type=bind,source=$(DIR)/.env,target=/var/www/.env -d $(IMAGE_NAME)

# debug: 
#   echo "OWNER" $OWNER

# build:
#   docker build -t $(GIT_TAG) .

# tag:
#   docker tag $(GIT_TAG) $(BUILD_TAG)
#   docker tag $(GIT_TAG) $(LATEST_TAG)

# login:
#   @docker login -u "$(DOCKER_USER)" -p "$(DOCKER_PASS)"

# push: login
#   docker push $(GIT_TAG)
#   docker push $(BUILD_TAG)
#   docker push $(LATEST_TAG)
